#!/bin/bash

BASE_REQ="requirements-base.txt"
SERVICES=("01-ingest-server" "02-device-manager" "03-analytics-alerts")

echo "🔄 Syncing requirements from $(pwd)/$BASE_REQ"

# Add warning to base requirements if not present
if ! grep -q "## Autogenerated" "$BASE_REQ"; then
  echo "## Autogenerated - Do not edit this file directly" >> "$BASE_REQ"
else
  echo "✅ Warning already present in base requirements"
fi

echo "📦 Rebuilding requirements.txt for all services..."
for service in "${SERVICES[@]}"; do
  if [[ -d "$service" ]]; then
    cp "$BASE_REQ" "$service/requirements.txt"
    echo "✅ Synced to $service"
  else
    echo "⚠️  Skipping $service (directory not found)"
  fi
done

echo "🎉 All done. Requirements successfully synced."
